default_language_version:
    python: python3.7
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: requirements-txt-fixer
      -   id: sort-simple-yaml
  -   repo: https://github.com/pre-commit/mirrors-autopep8
      rev: ''  # Use the sha / tag you want to point at
      hooks:
      -   id: autopep8
