# Generated by Django 3.0.6 on 2020-05-25 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocksList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstocks',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    primary_key=True, serialize=False, to='stocksList.Users', unique=True),
        ),
    ]
