# Generated by Django 3.0.6 on 2020-05-26 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocksList', '0002_auto_20200525_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='StocksList',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(
                    decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(
                    decimal_places=2, default=0, max_digits=10)),
                ('purchase_date', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('nemo_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='stocksList.Nemos')),
                ('user_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='stocksList.Users')),
            ],
        ),
        migrations.DeleteModel(
            name='UserStocks',
        ),
    ]
