# Generated by Django 3.0.6 on 2020-06-03 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocksList', '0003_auto_20200526_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockslist',
            name='nemo_id',
        ),
        migrations.RemoveField(
            model_name='stockslist',
            name='user_id',
        ),
        migrations.AddField(
            model_name='stockslist',
            name='nemo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockslist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='stocklist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Nemos',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
