# Generated by Django 3.0.6 on 2020-06-03 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocksList', '0004_auto_20200603_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockslist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='stockslist', to=settings.AUTH_USER_MODEL),
        ),
    ]
