# Generated by Django 3.0.6 on 2020-06-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocksList', '0006_auto_20200603_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockslist',
            old_name='price',
            new_name='purchasePrice',
        ),
    ]
