# Generated by Django 3.0.6 on 2020-06-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksList', '0007_auto_20200605_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockslist',
            name='saleTargetPrice',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10),
        ),
    ]
