# Generated by Django 3.0.6 on 2020-06-05 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocksList', '0008_stockslist_saletargetprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockslist',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='stockslist',
            name='purchaseDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
